server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud2023?rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345678
mybatis-plus:
  type-aliases-package: com.norelax.entities

#集成eureka配置
eureka:
  client:
    register-with-eureka: true #true表示需要向注册中心注册自己
    fetch-registry: true #true表示需要去检索服务
    service-url:
      #defaultZone: http://localhost:7001/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版，设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    instance:
      instance-id: cloud-provider-payment8001 #自定义实例id
      prefer-ip-address: true #访问路径可以显示IP地址