server:
  port: 9001
spring:
  application:
    name: cloudalibaba-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoint:
    web:
      exposure:
        include: '*'
  # Path: cloudalibaba-provider-payment9001/src/main/resources/application.yml

