server:
  port: 83

spring:
  application:
    name: cloudalibaba-consumer-nacos-order83
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://cloudalibaba-provider-payment